"""
cmd_status.py — Status dashboard và STATUS.md generation.

Usage:
    python scripts/pdt.py status              # Dashboard terminal
    python scripts/pdt.py status --update     # Cập nhật docs/STATUS.md
    python scripts/pdt.py status --json       # JSON output
"""

import json
from datetime import datetime
try:
    import fcntl
except ImportError:
    fcntl = None

from .config import ARTIFACT_DEPS, DOCS_DIR
from .frontmatter import scan_all_artifacts


def check_dependencies(results: dict) -> dict:
    """Check dependency satisfaction cho mỗi artifact type."""
    dep_status = {}
    for artifact_type, deps in ARTIFACT_DEPS.items():
        met = []
        unmet = []
        for dep in deps:
            dep_artifacts = results.get(dep, [])
            if not dep_artifacts:
                unmet.append(f"{dep} (not started)")
            else:
                has_approved = any(a["status"] == "approved" for a in dep_artifacts)
                has_draft = any(a["status"] in ("draft", "review") for a in dep_artifacts)
                if has_approved:
                    met.append(f"{dep} ✅")
                elif has_draft:
                    met.append(f"{dep} ⚠ draft")
                else:
                    unmet.append(f"{dep} (not started)")
        dep_status[artifact_type] = {"met": met, "unmet": unmet}
    return dep_status


def format_progress_bar(done: int, total: int, width: int = 20) -> str:
    """Render progress bar: [████████░░░░] 60%"""
    if total == 0:
        return "[ — ]"
    ratio = done / total
    filled = int(width * ratio)
    bar = "█" * filled + "░" * (width - filled)
    pct = int(ratio * 100)
    return f"[{bar}] {pct}%"


def format_dashboard(results: dict, dep_status: dict) -> str:
    """Format kết quả thành rich terminal dashboard."""
    lines = []
    lines.append("")
    lines.append("╔══════════════════════════════════════════════════════════╗")
    lines.append("║  📊 PROJECT STATUS DASHBOARD                            ║")
    lines.append("╚══════════════════════════════════════════════════════════╝")
    lines.append("")

    total_approved = 0
    total_types = len(ARTIFACT_DEPS)

    for artifact_type in ARTIFACT_DEPS:
        artifacts = results.get(artifact_type, [])
        deps = dep_status.get(artifact_type, {})

        if not artifacts:
            icon = "⬜"
            status_text = "not started"
            progress = ""
        else:
            statuses = [a["status"] for a in artifacts]
            if all(s == "approved" for s in statuses):
                icon = "✅"
                status_text = "approved"
                total_approved += 1
                progress = format_progress_bar(1, 1, 15)
            elif any(s == "review" for s in statuses):
                icon = "🔍"
                status_text = "in review"
                # Aggregate completeness
                done = sum(a["completeness_done"] for a in artifacts)
                total = sum(a["completeness_total"] for a in artifacts)
                progress = format_progress_bar(done, total, 15) if total > 0 else ""
            elif any(s == "draft" for s in statuses):
                icon = "📝"
                status_text = "draft"
                done = sum(a["completeness_done"] for a in artifacts)
                total = sum(a["completeness_total"] for a in artifacts)
                progress = format_progress_bar(done, total, 15) if total > 0 else ""
            else:
                icon = "❓"
                status_text = ", ".join(set(statuses))
                progress = ""

        line = f"  {icon} {artifact_type:<16} {status_text:<14} {progress}"
        lines.append(line)

        # Show files under each type
        if artifacts:
            for a in artifacts:
                comp = f" ({a['completeness']})" if a['completeness'] != '—' else ''
                lines.append(f"     └─ {a['file']}{comp}")

        # Show dependency warnings
        if deps.get("unmet"):
            lines.append(f"     ⚠  Needs: {', '.join(deps['unmet'])}")

    lines.append("")
    lines.append(f"  ─── Overall: {total_approved}/{total_types} types approved ───")
    lines.append("")

    return "\n".join(lines)


def generate_status_md(results: dict, dep_status: dict) -> str:
    """Generate docs/STATUS.md từ scan results."""
    today = datetime.now().strftime("%Y-%m-%d")
    lines = []

    lines.append("# Project Status Tracker")
    lines.append("")
    lines.append(f"> Auto-generated by `python scripts/pdt.py status --update` on {today}")
    lines.append("> Source of truth: frontmatter trong từng document.")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## Artifact Status")
    lines.append("")
    lines.append("| Artifact | File | Status | Completeness | Dependencies | Updated |")
    lines.append("|---|---|---|---|---|---|")

    for artifact_type in ARTIFACT_DEPS:
        artifacts = results.get(artifact_type, [])
        deps = dep_status.get(artifact_type, {})
        dep_str = "✅" if not deps.get("unmet") else "⚠ " + ", ".join(deps["unmet"])

        if not artifacts:
            lines.append(f"| {artifact_type} | — | ⬜ not started | — | {dep_str} | — |")
        else:
            for i, a in enumerate(artifacts):
                name = artifact_type if i == 0 else ""
                dep_col = dep_str if i == 0 else ""
                lines.append(f"| {name} | `{a['file']}` | {a['status']} | {a['completeness']} | {dep_col} | {a['updated']} |")

    lines.append("")

    # Readiness
    total_approved = sum(
        1 for at in ARTIFACT_DEPS
        if results.get(at) and all(a["status"] == "approved" for a in results[at])
    )
    lines.append("## Readiness")
    lines.append("")
    lines.append(f"- **Handoff Ready**: {total_approved}/{len(ARTIFACT_DEPS)} artifact types approved")
    lines.append("")

    # Dependency Graph
    lines.append("## Dependency Graph")
    lines.append("")
    lines.append("```mermaid")
    lines.append("graph TD")
    lines.append('    Vision --> PRD')
    lines.append('    Brief["Feature Brief"] --> PRD')
    lines.append('    PRD --> Flows')
    lines.append('    PRD --> SRS')
    lines.append('    Flows --> Mockup')
    lines.append('    PRD --> Mockup')
    lines.append('    SRS --> TDD')
    lines.append('    Mockup --> TDD')
    lines.append('    Decisions -.-> TDD')
    lines.append('    TDD --> Gate{"Review Gate"}')
    lines.append('    Mockup --> Gate')
    lines.append('    SRS --> Gate')
    lines.append('    Flows --> Gate')
    lines.append('    Decisions --> Gate')
    lines.append('    Gate -->|Pass| Handoff')
    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append(f"_Cập nhật: {today} | Generate: `python scripts/pdt.py status --update`_")
    lines.append("")

    return "\n".join(lines)


def cmd_status(args: list[str]):
    """Entry point cho `pdt status`."""
    results = scan_all_artifacts()
    dep_status = check_dependencies(results)

    if "--json" in args:
        output = {
            "generated": datetime.now().isoformat(),
            "artifacts": {k: [
                {kk: vv for kk, vv in a.items() if kk != "abs_path"}
                for a in v
            ] for k, v in results.items()},
            "dependencies": dep_status,
        }
        print(json.dumps(output, indent=2, ensure_ascii=False))
        return

    if "--update" in args:
        content = generate_status_md(results, dep_status)
        status_path = DOCS_DIR / "STATUS.md"
        
        with open(status_path, "w", encoding="utf-8") as f:
            if fcntl:
                fcntl.flock(f, fcntl.LOCK_EX)
            try:
                f.write(content)
                f.flush()
            finally:
                if fcntl:
                    fcntl.flock(f, fcntl.LOCK_UN)
                    
        print(f"✅ Updated {status_path}")
        print()

    print(format_dashboard(results, dep_status))
